### ISSUE TITLE
Beacon.java:32  未检测mItems是否为null，运行时会不断抛出空指针

### ISSUE THREAD

**Issue by junerver** [dingjikerbo/BluetoothKit#10]
```
E/miio-bluetooth: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.inuker.bluetooth.library.utils.proxy.ProxyBulk.safeInvoke(ProxyBulk.java:26)
    at com.inuker.bluetooth.library.utils.proxy.ProxyBulk.safeInvoke(ProxyBulk.java:34)
    at com.inuker.bluetooth.library.utils.proxy.ProxyInvocationHandler.handleMessage(ProxyInvocationHandler.java:102)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5682)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
    at com.inuker.bluetooth.library.beacon.Beacon.toString(Beacon.java:32)
    at com.junerver.bluetoothdemo.MainActivity$1.onDeviceFounded(MainActivity.java:41)
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.inuker.bluetooth.library.utils.proxy.ProxyBulk.safeInvoke(ProxyBulk.java:26) 
    at com.inuker.bluetooth.library.utils.proxy.ProxyBulk.safeInvoke(ProxyBulk.java:34) 
    at com.inuker.bluetooth.library.utils.proxy.ProxyInvocationHandler.handleMessage(ProxyInvocationHandler.java:102) 
    at android.os.Handler.dispatchMessage(Handler.java:107) 
    at android.os.Looper.loop(Looper.java:194) 
    at android.app.ActivityThread.main(ActivityThread.java:5682) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
    at com.inuker.bluetooth.library.beacon.Beacon.toString(Beacon.java:32)
    at com.junerver.bluetoothdemo.MainActivity$1.onDeviceFounded(MainActivity.java:41)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.inuker.bluetooth.library.utils.proxy.ProxyBulk.safeInvoke(ProxyBulk.java:26)
    at com.inuker.bluetooth.library.utils.proxy.ProxyBulk.safeInvoke(ProxyBulk.java:34)
    at com.inuker.bluetooth.library.utils.proxy.ProxyInvocationHandler.handleMessage(ProxyInvocationHandler.java:102)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5682)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

**Comment by dingjikerbo** [comment]
已修复了，请更新到1.3.2
