### ISSUE TITLE
BleGattProfile.toString Exception

### ISSUE THREAD

**Issue by Creky** [dingjikerbo/BluetoothKit#7]
>  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
at com.inuker.bluetooth.library.model.BleGattService.toString(BleGattService.java:79)
at java.lang.String.valueOf(String.java:2683)
at java.lang.StringBuilder.append(StringBuilder.java:129)
at com.inuker.bluetooth.library.model.BleGattProfile.toString(BleGattProfile.java:120)

**Comment by dingjikerbo** [comment]
这个会尽快修复

**Comment by dingjikerbo** [comment]
已修复，请更新到1.2.6
